---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: Remove apache2 package
    apt:
      name: apache2
      state: absent

  - name: Instal fake package
    apt: 
      name: emaprado_fake


