---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes

  - name: Remove apache2 package
    apt:
      name: apache2
      state: absent

  - name: Remove tmux
    apt: 
      name: tmux
      state: absent
