---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes

  - name: Remove php for CentOS servers
    apt:
      name: php
      state: absent
    when: ansible_distribution == "CentOS"


- hosts: web_servers
  become: true
  tasks:

  - name: Remove tmux package
    apt:
      name: tmux
      state: absent


- hosts: db_servers
  become: true
  tasks:

  - name: Remove apache2 and vim-nox package for Ubuntu servers
    apt:
      name:
        - apache2
        - vim-nox
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: Remove fake package
    apt:
      name: emaprado_fake
      state: absent


